development:
  adapter: postgresql
  encoding: unicode
  database: coinery_development
  pool: 5
  username: johncapecelatro
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: coinery_test
  pool: 5
  username: johncapecelatro 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: coinery_production
  pool: 5
  username: johncapecelatro 
  password:
